version: '3'

services:
  db:
    image: postgres:12.12-alpine
    ports:
      - "127.0.0.1:5447:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
    volumes:
      - pg-data:/var/lib/postgresql/data0
      - ./configs/docker/initdb.d:/docker-entrypoint-initdb.d
  redis:
    image: redis:7-alpine
    ports:
      - "127.0.0.1:6384:6379"
    volumes:
      - redis-data:/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: 123456
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  redis-data:
  pg-data:
  rabbitmq-data:

networks:
  default:
    driver: bridge